[project]
name = "tcc-dairycolletor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bert-score>=0.3.13",
    "chromadb>=1.5.0",
    "curl-cffi>=0.14.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.135.3",
    "groq>=1.0.0",
    "httpx>=0.28.1",
    "langchain>=1.2.10",
    "langchain-community>=0.4.1",
    "langchain-ollama>=1.0.1",
    "mosestokenizer>=1.2.1",
    "nltk>=3.9.2",
    "ollama>=0.6.1",
    "openai>=2.8.1",
    "pandas>=2.3.3",
    "parsel>=1.10.0",
    "pydantic-core>=2.41.5",
    "pymupdf>=1.27.1",
    "pypdf>=6.7.0",
    "rouge-score>=0.1.2",
    "scipy>=1.17.1",
    "selenium>=4.38.0",
    "tiktoken>=0.12.0",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "unsloth>=2026.1.4",
    "uvicorn>=0.40.0",
]

[tool.uv.workspace]
members = [
    "api",
]
